import express from 'express';

const app = express();
app.use(express.json());

function deterministicSeed(input: string): number {
  // simple deterministic hash (FNV-1a like mix)
  let h = 2166136261;
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  return h >>> 0;
}

app.post('/generate', (req, res) => {
  const input = JSON.stringify(req.body || {});
  const seed = deterministicSeed(input);
  const world = {
    id: seed.toString(),
    title: 'Mock World',
    description: 'A deterministic narrative world generated by Narrative World Director mock.',
    input,
    generatedAt: new Date().toISOString()
  };
  res.json({ world });
});

const PORT = 4001;
app.listen(PORT, () => {
  console.log(`Narrative World Director mock listening on port ${PORT}`);
});

export default app;
